import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback } from "@radix-ui/react-avatar";
const StudentTable = ({ alumnos, onDetalle }) => {
    return (_jsxs("div", { className: "overflow-x-auto", children: [_jsxs("table", { className: "w-full", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b", children: [_jsx("th", { className: "text-left py-3 px-4 font-medium text-gray-600", children: "Alumno" }), _jsx("th", { className: "text-left py-3 px-4 font-medium text-gray-600", children: "Matr\u00EDcula" }), _jsx("th", { className: "text-center py-3 px-4 font-medium text-gray-600", children: "Semestre" }), _jsx("th", { className: "text-center py-3 px-4 font-medium text-gray-600", children: "Conferencias" }), _jsx("th", { className: "text-center py-3 px-4 font-medium text-gray-600", children: "Actividades" }), _jsx("th", { className: "text-center py-3 px-4 font-medium text-gray-600", children: "Total" }), _jsx("th", { className: "text-center py-3 px-4 font-medium text-gray-600", children: "Acciones" })] }) }), _jsx("tbody", { children: alumnos.map((a) => (_jsxs("tr", { className: "border-b hover:bg-gray-50", children: [_jsx("td", { className: "py-4 px-4", children: _jsxs("div", { className: "flex items-center space-x-3", children: [_jsx(Avatar, { className: "h-10 w-10 bg-uaa-blue text-white flex items-center justify-center rounded-full", children: _jsx(AvatarFallback, { className: "text-sm font-semibold", children: a.nombre
                                                        .split(" ")
                                                        .map((n) => n[0])
                                                        .join("")
                                                        .slice(0, 2) }) }), _jsxs("div", { children: [_jsx("p", { className: "font-medium text-gray-900", children: a.nombre }), _jsx("p", { className: "text-sm text-gray-500", children: a.correo })] })] }) }), _jsx("td", { className: "py-4 px-4 text-gray-600", children: a.matricula }), _jsx("td", { className: "py-4 px-4 text-center", children: _jsxs("span", { className: "inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-uaa-blue text-white", children: [a.semestre, "\u00B0"] }) }), _jsx("td", { className: "py-4 px-4 text-center text-blue-600 font-semibold text-lg", children: a.asistenciasConferencias }), _jsx("td", { className: "py-4 px-4 text-center text-pink-600 font-semibold text-lg", children: a.asistenciasActividades }), _jsx("td", { className: "py-4 px-4 text-center text-green-600 font-bold text-lg", children: a.totalAsistencias }), _jsx("td", { className: "py-4 px-4 text-center", children: _jsx(Button, { size: "sm", variant: "outline", onClick: () => onDetalle(a), children: "Ver Detalle" }) })] }, a.id))) })] }), alumnos.length === 0 && (_jsx("div", { className: "text-center py-8", children: _jsx("p", { className: "text-gray-500", children: "No hay alumnos para mostrar" }) }))] }));
};
export default StudentTable;
